kind: Service
apiVersion: v1
metadata:
  name: audit
  labels:
    app: audit
spec:
  selector:
    app: audit
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  labels:
    app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "audit"
        dapr.io/app-port: "8084"
        dapr.io/enable-api-logging: "true"
#        dapr.io/config: "dapr-config"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
        - name: audit
          image: eminetto/audit:latest
          ports:
            - containerPort: 8084
          imagePullPolicy: Always
