kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-auth-initdb-pv-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/elton.minetto/Developer/poc-dapr/auth/ops/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-auth-initdb-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - port: 3306
      name: high
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: auth_pwd
            - name: MYSQL_DATABASE
              value: auth_db
            - name: MYSQL_USER
              value: auth_user
            - name: MYSQL_PASSWORD
              value: auth_pwd
          image: mysql:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-initdb
      volumes:
        - name: mysql-initdb
          persistentVolumeClaim:
            claimName: mysql-auth-initdb-pv-claim
